
VACUUM VERBOSE ANALYZE caom2.Observation;
VACUUM VERBOSE ANALYZE caom2.Plane;
VACUUM VERBOSE ANALYZE caom2.Artifact;
VACUUM VERBOSE ANALYZE caom2.Part;
VACUUM VERBOSE ANALYZE caom2.Chunk;

VACUUM VERBOSE ANALYZE caom2.ObservationMetaReadAccess;
VACUUM VERBOSE ANALYZE caom2.PlaneMetaReadAccess;
VACUUM VERBOSE ANALYZE caom2.PlaneDataReadAccess;

