openapi: 3.1.0
info:
  title: Prototype CAOM TAP service
  version: '2.0-BETA'
  description: |
    This is a prototype WD-CAOM-2.5 TAP service with WD-ObsCore-1.2 views.
    
    Tables: caom2.Observation, caom2.Plane, caom2.Artifact, caom2.ArtifactDescription,
    caom2.DeletedObservationEvent, caom2.DeletedArtifactDescriptionEvent.
    
    IVOA views:  ivoa.ObsCore, ivoa.ObsCore_radio.

servers:
    - url: /argus

tags:
    - name: TAP Query
    - name: DALI Examples
    - name: VOSI Capabilities
    - name: VOSI Table Metadata

paths:
    /sync:
        $ref: ./openapi/tap/tap-sync.yaml
    /async:
        $ref: ./openapi/tap/tap-async.yaml
    /async/{jobID}:
        $ref: ./openapi/uws/uws-job.yaml
    /async/{jobID}/phase:
        $ref: ./openapi/uws/uws-job-phase.yaml
    /async/{jobID}/results/result:
        $ref: ./openapi/tap/tap-result.yaml

    /capabilities:
        $ref: ./openapi/vosi/vosi-capabilities.yaml

    /tables:
        $ref: ./openapi/vosi/vosi-tableset.yaml
    /tables/{name}:
        $ref: ./openapi/vosi/vosi-table.yaml
        
    /examples:
        $ref: ./openapi/dali/dali-examples.yaml
