
VACUUM VERBOSE ANALYZE <schema>.Observation;
VACUUM VERBOSE ANALYZE <schema>.Plane;
VACUUM VERBOSE ANALYZE <schema>.Artifact;
VACUUM VERBOSE ANALYZE <schema>.Part;
VACUUM VERBOSE ANALYZE <schema>.Chunk;

VACUUM VERBOSE ANALYZE <schema>.HarvestState;
VACUUM VERBOSE ANALYZE <schema>.HarvestSkipURI;
