#!/bin/bash

usage()
{
    echo "caom2harvestAll"
    echo
    echo "This is a simple wrapper script that runs caom2harvester for "
    echo "each source database. It is intended for direct use in a crontab"
    echo "with a recommended interval of 5+ minutes."
    echo
    echo "usage: caom2harvestAll <config>"
    echo
    echo "config format:"
    echo
    echo "GRCERT=/path/to/valid.pem" 
    echo "LOGDIR=/path/to/logs"
    echo "TARGET=<server>                    (e.g. cvodb0)"
    echo "SOURCES=<server>.<database> ...    (e.g. SYBASE.cfht)"   
    echo "ACDA=<server>.<database> ...       (e.g. SYBASE.cfht)"
    echo
    echo "GRCERT:  A proxy certficate for the owner of archive groups to be created."
    echo
    echo "LOGDIR:  This is the path to log files from the invoked applications."
    echo "         A subdirectory for the target cvodb server will be created if"
    echo "         necessary. Logfiles will be timestamped. The control file used"
    echo "         to avoid running multiple instances with the same source DB also"
    echo "         gets stored here so *do not* edit this setting while any cron"
    echo "         jobs are running."
    echo
    echo "TARGET:  This is the target PostgreSQL server. It supports a single"
    echo "         value so harvesting to each server is controlled by a separate"
    echo "         cron job."
    echo
    echo "SOURCES: This is the list of source (sybase) databases. The server and"
    echo "         database name have to be resolved in the users $HOME/.dbrc file"
    echo "         for credentials and connection information (read-only)."
    echo
    echo "ACDA:    This is a list of variables whose name is one of the database names"
    echo "         in SOURCES (e.g. without the server name and whose value is the"
    echo "         archive name for invoking the accessControlDA." 
    echo
    echo "         The accessControlDA will be invoked (before caom2harvester) with"
    echo "         --mode=asset --archive=<archive>. The accessControlDA application"
    echo "         has internal mechanisms to get credentials and may also have docs."
    echo
    echo "         Example: SOURCES=\"SYBASE.cfht SYBASE.hstcaom2 SYBASE.macho\""
    echo "                  ACDA=hstcaom2"
    echo "                  hstcaom2=HST"
    echo "         Here, hstcaom2 is the database name and HST is the archive name."
    echo
    echo "WARNING: Using file or path names with spaces is likely to break this script."
}

if [ -z "$1" ]; then
    usage
    exit 1
fi

CONFIG="$1"
if [[ ! -f $CONFIG ]]; then
    echo "config file not found: $CONFIG"
    usage
    exit 1
fi

. "$CONFIG"

if [ -z $GRCERT ]; then
    echo "missing GRCERT from $CONFIG"
    usage
    exit 1
elif [ ! -f $GRCERT ]; then
    echo "certificate file not found: $GRCERT"
    usage
    exit 1
fi

if [ -z $LOGDIR ]; then
    echo "missing LOGDIR from $CONFIG"
    usage
    exit 1
fi

if [ -z $TARGET ]; then
    echo "missing TARGET from $CONFIG"
    usage
    exit 1
fi

if [ -z "$SOURCES" ]; then
    echo "missing SOURCES from $CONFIG"
    usage
    exit 1
fi

LOGDIR=${LOGDIR}/$TARGET
test -d $LOGDIR || echo "creating logdir: ${LOGDIR}" && mkdir -p $LOGDIR

LOG_SUFFIX=$(date +"%Y%m%d%H%M%S")


for src in $SOURCES; do
    SOURCE="${src}.dbo"
    DEST="${TARGET}.cvodb.caom2"
    LOG=$LOGDIR/${SOURCE}-${LOG_SUFFIX}.log
    ACLOG=$LOGDIR/${SOURCE}-ac-${LOG_SUFFIX}.log

    ARC=""
    if [ -e $LOGDIR/$SOURCE.run ]; then
        echo "blocked: $LOG_SUFFIX" >> $LOGDIR/$SOURCE.run
    else
        touch $LOG
        touch $LOGDIR/$SOURCE.run
        CUR_UTC=$(date --utc +"%Y-%m-%dT%H:%M:%S.000")

        for ac in $ACDA; do
            db=$(echo $src | awk -F '.' '{print $2}')
            if [ $db == $ac ]; then
## tricksy bash: ${!ac} is the value of a variable named $ac
                for ARC in ${!ac}; do
                    $CADC_ROOT/scripts/caom2AccessControlDA -v --archive=$ARC --database=$SOURCE --cert=$GRCERT &> $ACLOG
                done
            fi
        done
        
        BATCH_SIZE=10
        BATCH_FACTOR=20000
        $CADC_ROOT/scripts/caom2harvester -v --maxDate=$CUR_UTC --batchSize=$BATCH_SIZE --batchFactor=$BATCH_FACTOR --source=$SOURCE --destination=$DEST &> $LOG

        if [ $? == 0 ]; then
            rm $LOGDIR/$SOURCE.run
        fi
    fi
done
