#!/bin/bash

# Resolve links: $0 may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
APP_BASE_NAME=`dirname "$PRG"`
APP_NAME="caom2harvester"

export CAOM2HARVESTER_OPTS="-Dca.nrc.cadc.caom2.harvester.Main.ecf=true" 
$APP_BASE_NAME/$APP_NAME $@
