name: Java CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
  
    - name: build and test caom2
      run: cd caom2 && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test caom2-compute
      run: cd caom2-compute && ../gradlew --info clean assemble javadoc checkstyleMain install
    
    - name: build and test caom2-artifact-resolvers
      run: cd caom2-artifact-resolvers && ../gradlew --info clean assemble javadoc checkstyleMain install

# OBSOLETE
#    - name: build and test fits2caom2
#      run: cd fits2caom2 && ../gradlew --info clean build javadoc install

    - name: build and test caom2-validator
      run: cd caom2-validator && ../gradlew --info clean build
##
    - name: build and test caom2-access-control
      run: cd caom2-access-control && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test caom2-persist
      run: cd caom2-persist && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test caom2-repo
      run: cd caom2-repo && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test caom2persistence
      run: cd caom2persistence && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test caom2-artifact-sync
      run: cd caom2-artifact-sync && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test caom2-artifact-store-si
      run: cd caom2-artifact-store-si && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test caom2-repo
      run: cd caom2-repo && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test caom2-repo-server
      run: cd caom2-repo-server && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test caom2-test-repo
      run: cd caom2-test-repo && ../gradlew --info clean build javadoc checkstyleMain install

    - name: build and test caom2harvester
      run: cd caom2harvester && ../gradlew --info clean build javadoc checkstyleMain

    - name: build and test caom2-collection-validator
      run: cd caom2-collection-validator && ../gradlew --info clean build javadoc checkstyleMain

    - name: build and test caom2-remove
      run: cd caom2-remove && ../gradlew --info clean build javadoc checkstyleMain

    - name: build and test caom2-artifact-discover
      run: cd caom2-artifact-discover && ../gradlew --info clean build javadoc checkstyleMain

    - name: build and test caom2-artifact-download
      run: cd caom2-artifact-download && ../gradlew --info clean build javadoc checkstyleMain             

    - name: build and test caom2-tap
      run: cd caom2-tap && ../gradlew clean build javadoc install

    - name: build and test caom2-tap-server
      run: cd caom2-tap-server && ../gradlew clean build javadoc install
    
    - name: build and test caom2-datalink-server
      run: cd caom2-datalink-server && ../gradlew clean build javadoc install
    
    - name: build and test caom2-meta-server
      run: cd caom2-meta-server && ../gradlew clean build javadoc install
    
    - name: build and test caom2-pkg-server
      run: cd caom2-pkg-server && ../gradlew clean build javadoc install
    
    - name: build and test caom2-soda-server
      run: cd caom2-soda-server && ../gradlew clean build javadoc install

## applications
    - name: build and test icewind 
      run: cd icewind && ../gradlew --info clean build checkstyleMain

    - name: build and test torkeep 
      run: cd torkeep && ../gradlew --info clean build checkstyleMain
      
    - name: build and test argus 
      run: cd argus && ../gradlew --info clean build checkstyleMain

    - name: build and test bifrost 
      run: cd bifrost && ../gradlew --info clean build checkstyleMain

