name: Java CI with Gradle

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    
    - name: build and test caom2-tap
      run: cd caom2-tap && ../gradlew clean build javadoc install

    - name: build and test caom2-tap-server
      run: cd caom2-tap-server && ../gradlew clean build javadoc install
    
    - name: build and test caom2-datalink-server
      run: cd caom2-datalink-server && ../gradlew clean build javadoc install
    
    - name: build and test caom2-meta-server
      run: cd caom2-meta-server && ../gradlew clean build javadoc install
    
    - name: build and test caom2-pkg-server
      run: cd caom2-pkg-server && ../gradlew clean build javadoc install
    
    - name: build and test caom2-soda-server
      run: cd caom2-soda-server && ../gradlew clean build javadoc install
